version: '3.9'

services:
    rezapp-backend:
        build: src/backend
        image: rezapp-backend
        environment:
            - OTEL_ACTIVE=true
        volumes:
            - database:/database
            - images:/app/images
            - ./pipeline/ormconfig.json:/app/ormconfig.json

    rezapp-frontend:
        build: src/frontend
        image: rezapp-frontend
        environment:
            BACKEND_URL: http://rezapp-proxy:8000
            AUTH_PROVIDER_URL: http://rezapp-proxy:8000/auth
        ports:
            - 3000:3000

    rezapp-proxy:
        image: kong/kong-gateway:3.1.1.1
        volumes:
            - ./kong-local.yaml:/kong/kong.yaml
        environment:
            KONG_DATABASE: 'off'
            KONG_DECLARATIVE_CONFIG: /kong/kong.yaml
            KONG_OPENTELEMETRY_TRACING: all
        ports:
            - 8000:8000

    rezapp-auth-provider:
        build: src/auth-provider
        image: rezapp-auth-provider
        env_file:
            - .env

    rezapp-zipkin:
        image: openzipkin/zipkin-slim

    rezapp-otel:
        image: otel/opentelemetry-collector-contrib
        command: '--config=/etc/otelcol/config.yaml'
        volumes:
            - ./otel-local.yaml:/etc/otelcol/config.yaml

volumes:
    database:
    images:
