version: '3.9'

services:
    rezapp-backend:
        image: ghcr.io/neatoro/rezapp/rezapp-backend:latest
        volumes:
            - database:/database
            - images:/app/images
            - ./ormconfig.json:/app/ormconfig.json

    rezapp-frontend:
        image: ghcr.io/neatoro/rezapp/rezapp-frontend:latest
        environment:
            BACKEND_URL: http://rezapp-proxy:8000
            AUTH_PROVIDER_URL: http://rezapp-proxy:8000/auth

    rezapp-proxy:
        image: kong/kong-gateway:3.1.1.1
        volumes:
            - ./proxy:/kong/declarative
        environment:
            KONG_DATABASE: 'off'
            KONG_DECLARATIVE_CONFIG: /kong/declarative/kong.yaml
        ports:
            - 8976:8000

    rezapp-auth-provider:
        image: ghcr.io/neatoro/rezapp/rezapp-auth-provider:latest
        env_file:
            - .env

volumes:
    database:
    images:
