name: ci

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and export backend
        uses: docker/build-push-action@v3
        with:
          context: src/backend
          tags: rezapp-backend:latest
          outputs: type=docker,dest=/tmp/backend.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: backend
          path: /tmp/backend.tar

  api-tests:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: backend
          path: /tmp

      - name: Load image
        run: |
          docker load --input /tmp/backend.tar
          docker image ls -a

      - name: Start backend container
        run: |
          docker run -d --rm --name rezapp-backend -p 8080:8080 -v ./pipeline/ormconfig.json:/app/ormconfig.json rezapp-backend

      - name: Install API tests
        run: |
          docker cp integration-tests/api-tests rezapp-backend:/api-tests
          docker exec rezapp-backend npm ci --prefix /api-tests

